name: Deploy API to Server

#akan melkaukan deploy ketika push ke branch main
on:
  push:
    branches:
      - main

#jalankan docker dan install
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v3
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    #Login to docker hub
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}  
    #build dan push dockerfile kedalam dockerhub
    -
      name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/x-tiev:latest
        
  #melakukan deploy menggunakan docker
  deploy-prod:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      #connect kedalam server menggunakan SSH
      - name: Connect to server using SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }} #ip public vm
          username: ${{ secrets.USERNAME }} # username ssh
          key: ${{ secrets.KEY }} # id_ecdsa local
          port: ${{ secrets.PORT }} #port
          script: |
            sudo docker stop backend-api
            sudo docker rm backend-api
            sudo docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/x-tiev:latest
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/x-tiev:latest
            sudo docker run -d -p 8080:8080 -e GOOGLE_CLOUD_CREDENTIALS_PATH=${{ secrets.GOOGLE_CLOUD_CREDENTIALS_PATH }} -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} -e JWT_SECRET=${{ secrets.JWT_SECRET }} -e SERVERPORT=${{ secrets.SERVERPORT }} -e DBUSER=${{ secrets.DBUSER }} -e DBPASS=${{ secrets.DBPASS }} -e DBHOST=${{ secrets.DBHOST }} -e DBPORT=${{ secrets.DBPORT }} -e DBNAME=${{ secrets.DBNAME }} --name restapi ${{ secrets.DOCKERHUB_USERNAME }}/x-tiev:latest
